### ISSUE TITLE
No Mysql and Redis sample for KEDA 2.0 

### ISSUE THREAD

**Issue by Ritikaa96** [kedacore/samples#28]
Redis & mysql samples given in the repository are supported by KEDA v1, but there are no updated versions of the samples.

**Comment by tomkerkhove** [comment]
If you are willing to send a PR, we are always open for it!

**Comment by Ritikaa96** [comment]
@tomkerkhove
I just saw Jeff has already created an [issue](https://github.com/turbaszek/keda-example/issues/2) on @turbaszek keda-example repository. 
We only need to change few things in yaml according to migration document. I can suggest the changes to be done as i have recorded while trying the sample but the sample is already working well for v1 so i don't know if a whole new sample is required.

**Comment by turbaszek** [comment]
@Ritikaa96 if you would like to update the sample I would be happy to review it. I had Jeff's issue marked as "to be done" since December 🙈 

As per v1 version I can create separate branch for this sample to keep it as reference.

**Comment by Ritikaa96** [comment]
@turbaszek of course, sure. I'll update the mysql and redis one, i can try the httpScaler example but i think it will be better if you change that as it's latest and undocumented on the readme. PR coming your way.

**Comment by Ritikaa96** [comment]
@turbaszek @tomkerkhove  Created a [PR](https://github.com/turbaszek/keda-example/pull/3) on the repo. @turbaszek PTAL

**Comment by Ritikaa96** [comment]
Hi @tomkerkhove , the issue has been solved in this [pr](https://github.com/turbaszek/keda-example/pull/3).
