### ISSUE TITLE
Move samples under KEDA 2.0

### ISSUE THREAD

**Issue by Shubham82** [kedacore/samples#31]
Move the GCP PubSub sample i.e. [Google Cloud PubSub](https://github.com/kedacore/sample-go-gcppubsub) and Kafka sample i.e  [Azure Functions Kafka on Openshift 4](https://github.com/kedacore/sample-azure-functions-on-ocp4) under KEDA 2.0 as they have supported KEDA 2.0 version and also modify their links(acc. to keda 1.0) under KEDA 1.0

**Comment by Shubham82** [comment]
@tomkerkhove @zroubalik 
PTAL!

If it seems good then I will raise a PR for it!
Thanks

**Comment by tomkerkhove** [comment]
If they are upgraded then feel free to send a PR

**Comment by Shubham82** [comment]
yes, in their respective repo they have support for keda2.0.
I will soon create a PR for it.

**Comment by Shubham82** [comment]
Fixed it here #32
