### ISSUE TITLE
Kafka (0->1) + CPU (1->n)

### ISSUE THREAD

**Issue by hartblanc** [kedacore/samples#40]
Is it possible to use a KEDA scaler (e.g. Kafka) just for activation (0->1) scaling and a more typical CPU-based approach for 1->n scaling?

Would be great to see an example of this.

**Comment by zroubalik** [comment]
Yes, this scenario is supported out of the box: https://keda.sh/docs/2.13/scalers/cpu/

Please don't use this repo for questions.
